Repository Romeslayer/potSpotFE, pull requests merged in 2022-04, with the labels that each got.

#16 Component/status board
  pot-spot/src/components/App/App.css
  pot-spot/src/components/App/App.js
  pot-spot/src/components/Map/Map.js
  pot-spot/src/components/StatusBoard/StatusBoard.css
  pot-spot/src/components/StatusBoard/StatusBoard.js
  pot-spot/src/components/StatusUpdater/StatusUpdater.css
  pot-spot/src/components/StatusUpdater/StatusUpdater.js
Labels: enhancement, styling

#21 Add post request to add new pothole
  pot-spot/src/apiCalls.js
  pot-spot/src/components/App/App.js
  pot-spot/src/components/Form/Form.js
Labels: enhancement

#22 Added css to header and pothole / location info box
  pot-spot/src/assets/road1.jpeg
  pot-spot/src/assets/road2.jpeg
  pot-spot/src/assets/road3.jpeg
  pot-spot/src/assets/road4.jpeg
  pot-spot/src/components/Form/Form.css
  pot-spot/src/components/Header/Header.css
  pot-spot/src/components/Header/Header.js
  pot-spot/src/components/Map/Map.css
  pot-spot/src/components/Map/Map.js
  pot-spot/src/components/Pothole/Pothole.css
  pot-spot/src/components/Pothole/Pothole.js
  pot-spot/src/components/StatusBoard/StatusBoard.css
  pot-spot/src/components/StatusBoard/StatusBoard.js
Labels: enhancement

#23 Delete function/zl
  pot-spot/src/apiCalls.js
  pot-spot/src/components/App/App.js
  pot-spot/src/components/DisplayModal/DisplayModal.css
  pot-spot/src/components/DisplayModal/DisplayModal.js
  pot-spot/src/components/Form/Form.js
  pot-spot/src/components/Header/Header.js
  pot-spot/src/components/Pothole/Pothole.js
  pot-spot/src/components/PotholeContainer/PotholeContainer.css
  pot-spot/src/components/PotholeContainer/PotholeContainer.js
  pot-spot/src/components/PotholeDetail/PotholeDetail.css
  pot-spot/src/components/PotholeDetail/PotholeDetail.js
Labels: enhancement

#24 Cypress/zl
  pot-spot/cypress.json
  pot-spot/cypress/fixtures/example.json
  pot-spot/cypress/fixtures/profile.json
  pot-spot/cypress/fixtures/users.json
  pot-spot/cypress/integration/1-getting-started/todo.spec.js
  pot-spot/cypress/integration/2-advanced-examples/actions.spec.js
  pot-spot/cypress/integration/2-advanced-examples/aliasing.spec.js
  pot-spot/cypress/integration/2-advanced-examples/assertions.spec.js
  pot-spot/cypress/integration/2-advanced-examples/connectors.spec.js
  pot-spot/cypress/integration/2-advanced-examples/cookies.spec.js
  pot-spot/cypress/integration/2-advanced-examples/cypress_api.spec.js
  pot-spot/cypress/integration/2-advanced-examples/files.spec.js
  pot-spot/cypress/integration/2-advanced-examples/local_storage.spec.js
  pot-spot/cypress/integration/2-advanced-examples/location.spec.js
  pot-spot/cypress/integration/2-advanced-examples/misc.spec.js
  pot-spot/cypress/integration/2-advanced-examples/navigation.spec.js
  pot-spot/cypress/integration/2-advanced-examples/network_requests.spec.js
  pot-spot/cypress/integration/2-advanced-examples/querying.spec.js
  pot-spot/cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  pot-spot/cypress/integration/2-advanced-examples/traversal.spec.js
  pot-spot/cypress/integration/2-advanced-examples/utilities.spec.js
  pot-spot/cypress/integration/2-advanced-examples/viewport.spec.js
  pot-spot/cypress/integration/2-advanced-examples/waiting.spec.js
  pot-spot/cypress/integration/2-advanced-examples/window.spec.js
  pot-spot/cypress/integration/home_spec.js
  pot-spot/cypress/integration/manage_pothole_spec.js
  pot-spot/cypress/integration/pothole_spec.js
  pot-spot/cypress/integration/status_board_spec.js
  pot-spot/cypress/plugins/index.js
  pot-spot/cypress/support/commands.js
  pot-spot/cypress/support/index.js
  pot-spot/src/components/Header/Header.js
  pot-spot/src/components/StatusBoard/StatusBoard.css
  pot-spot/src/components/StatusBoard/StatusBoard.js
  pot-spot/src/components/StatusUpdater/StatusUpdater.js
Labels: testing

#25 Add Procfile
  pot-spot/Procfile
Labels: enhancement

#26 Cypress2/zl
  pot-spot/cypress/integration/home_spec.js
  pot-spot/cypress/integration/manage_pothole_spec.js
  pot-spot/cypress/integration/pothole_spec.js
  pot-spot/cypress/integration/status_board_spec.js
  pot-spot/src/components/Header/Header.js
  pot-spot/src/components/Pothole/Pothole.js
  pot-spot/src/components/StatusBoard/StatusBoard.js
Labels: testing

#29 Feature/readme
  README.md
  public/index.html
  src/assets/pothole-marker.png
  src/assets/potspot-functionality.gif
  src/assets/status-board-delete-ph.gif
  src/components/App/App.css
  src/components/Form/Form.css
  src/components/Pothole/Pothole.css
  src/components/Pothole/Pothole.js
Labels: documentation, styling

#30 Add api key and favicon
  public/pothole-marker.png
  src/components/Map/Map.js
Labels: enhancement

#31 Update README
  README.md
Labels: enhancement
